comment_parser: Make python-magic an optional dependency.
Users may use only extract_comments_from_str, which does not require
libmagic.

>>> from comment_parser import comment_parser
>>> comment_parser.extract_comments('foo.c', mime='text/x-c')
[Comment( Prints Hello World, 4, False)]
>>> comment_parser.extract_comments('foo.c')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jraviles/projects/src/comment_parser/comment_parser/comment_parser.py", line 78, in extract_comments
    return extract_comments_from_str(code.read(), mime)
  File "/home/jraviles/projects/src/comment_parser/comment_parser/comment_parser.py", line 97, in extract_comments_from_str
    raise ImportError('python-magic was not imported')
ImportError: python-magic was not imported

Closes #21